services:
  clash:
    image: dreamacro/clash:latest
    container_name: clash
    restart: unless-stopped
    ports:
      - "127.0.0.1:7890:7890"  # 混合代理端口，仅限本机访问
      - "127.0.0.1:7891:7891"  # SOCKS5代理，仅限本机访问
      - "9090:9090"  # API端口，允许Docker内部访问
    volumes:
      - ./config:/root/.config/clash
    environment:
      - TZ=Asia/Shanghai
    networks:
      - clash_network

  yacd:
    image: haishanh/yacd:latest
    container_name: yacd
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - CLASH_API_BASE_URL=http://clash:9090
      - CLASH_API_SECRET=x2S2ep2PmmgopYvXeI7dOn3Wxjy1bVF3oqQNjtfVDOiQnFDCnWYPwZeZseGvTlEt
    depends_on:
      - clash
    networks:
      - clash_network

networks:
  clash_network:
    driver: bridge 